name: Публикация релиза

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    uses: autumn-library/workflows/.github/workflows/release.yml@v1
    with:
      package_mask: "benchmark-*.ospx"
      dotnet_version: "8.x.x"
      locale: "en_US"
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}